### ISSUE TITLE
Handling stage and prod at the same time is difficult

### ISSUE THREAD

**Issue by mikix** [edx/frontend-auth#18]
I have a vague understanding that the current situation is that frontend-auth cookies have the same name in stage or prod. This was causing some issues, among which was the discovery service (hosted on DNS names like stage-edx-discovery.edx.org) not being able to use the stage JWTs.

I don't know the full context there. But the recommendation was to move to new-style DNS names (discovery.stage.edx.org). We tried to do that, but due to the difficulties with installing a dual-wildcard SSL cert (to be able to serve stage discovery off both names), a hard cutover to the new name was the plan (and just quickly fix all the stage pointers). But since whitelabels have the same problem, but may need a SSL cert fix anyway, we rolled that back to rethink and regroup.

So devops has asked me to come back to frontend-auth and ask some version of "can frontend-auth handle stage and prod in such a way that everything works without DNS changes?"

**Comment by mikix** [comment]
Pinging @douglashall and @feanil to hash this out.

**Comment by douglashall** [comment]
@mikix @feanil I'm currently working on fixing part of this issue by making the cookie names distinct across different environments. Should be done this week. I don't think this will resolve the DNS issue on stage, however, because we currently set the auth-related cookie domain to `stage.edx.org`. I suppose we could change that to be `edx.org`, but I'm unsure of the downstream impacts of such a change.

**Comment by mikix** [comment]
OK. Doug, could we just do `.edx.org` for the stage cookie too? That would cover these legacy DNS names.

**Comment by douglashall** [comment]
Maybe? Like I said, I'm not sure what the downstream impacts of that would be.

**Comment by nasthagiri** [comment]
Which legacy DNS WL names do we still need to support on stage?

**Comment by mikix** [comment]
@nasthagiri at least:
```
stage-cmeonline-discovery.edx.org
stage-mitxpro-discovery.edx.org
stage-edx-discovery-catalog.edx.org
stage-wharton-discovery.edx.org
```

**Comment by nasthagiri** [comment]
And which one of those is actually going to affect end-2-end tests?

We have only 2 WL sites on Prod.  I don't believe we need to support 4 on stage at this point.

@tuchfarber @georgebabey  Can you add context on which WL sites on stage is really still needed for testing?

**Comment by tuchfarber** [comment]
`stage-cmeonline-discovery.edx.org` => Being used in prod
`stage-mitxpro-discovery.edx.org` => Being used in prod
`stage-edx-discovery-catalog.edx.org` => Not WL. edX's internal deployment name for discovery. 
`stage-wharton-discovery.edx.org` => Still **technically** in prod, but only because it hasn't been decommissioned yet. 

Am I to assume from this discussion that the triple DNS names (`environment-deployment-service.edx.org`) are legacy at this time? As far I know I know the triples are still the standard and "pretty" DNS names `discovery.edx.org` just CNAMEs that point to them.

It's also not just e2e tests that fail either, LMS and ecommerce break when they can't talk to discovery due to SSL errors. 

If we want to rename `stage-edx-discovery.edx.org` to `discovery.stage.edx.org`, and keep the existing WL sites the same, we'd need to (amongst other things) set up discovery with multiple ELBs like we do with our other apps (courses, ecommerce, etc) so different hostnames can return different certs. Currently all discovery DNS records point to the same ELB, causing the issue with not being able to have multiple certs. Not sure if discovery was set up this way on purpose, or if it's just a sign of when it was written.

**Comment by mikix** [comment]
Nothing to do here for frontend-auth after all. We're working with devops to support the right ssl certs.
